import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Home | Contact App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <div className="min-h-screen max-w-md mx-auto">{children}</div>
      </body>
    </html>
  );
}
